// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: rpc/proxy/proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_rpc_proxy_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proxy_proto_rawDescGZIP(), []int{0}
}

type ForwardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	RequestBody   []byte                 `protobuf:"bytes,3,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"` // 原始请求体
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReq) Reset() {
	*x = ForwardReq{}
	mi := &file_rpc_proxy_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReq) ProtoMessage() {}

func (x *ForwardReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReq.ProtoReflect.Descriptor instead.
func (*ForwardReq) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ForwardReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ForwardReq) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *ForwardReq) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ForwardResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatusCode       int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseBody     []byte                 `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Headers          map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LatencyMs        int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	UpstreamId       string                 `protobuf:"bytes,7,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForwardResp) Reset() {
	*x = ForwardResp{}
	mi := &file_rpc_proxy_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResp) ProtoMessage() {}

func (x *ForwardResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResp.ProtoReflect.Descriptor instead.
func (*ForwardResp) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForwardResp) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *ForwardResp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardResp) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ForwardResp) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ForwardResp) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ForwardResp) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

type ProxyStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests  int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	ActiveRequests int32                  `protobuf:"varint,2,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	ProviderCount  int32                  `protobuf:"varint,3,opt,name=provider_count,json=providerCount,proto3" json:"provider_count,omitempty"`
	Healthy        bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProxyStatus) Reset() {
	*x = ProxyStatus{}
	mi := &file_rpc_proxy_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStatus) ProtoMessage() {}

func (x *ProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStatus.ProtoReflect.Descriptor instead.
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyStatus) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ProxyStatus) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *ProxyStatus) GetProviderCount() int32 {
	if x != nil {
		return x.ProviderCount
	}
	return 0
}

func (x *ProxyStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type BreakerStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakerStatsReq) Reset() {
	*x = BreakerStatsReq{}
	mi := &file_rpc_proxy_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakerStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakerStatsReq) ProtoMessage() {}

func (x *BreakerStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakerStatsReq.ProtoReflect.Descriptor instead.
func (*BreakerStatsReq) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *BreakerStatsReq) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type BreakerStatsResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // closed / open / half-open
	TotalFailures   int64                  `protobuf:"varint,2,opt,name=total_failures,json=totalFailures,proto3" json:"total_failures,omitempty"`
	TotalSuccesses  int64                  `protobuf:"varint,3,opt,name=total_successes,json=totalSuccesses,proto3" json:"total_successes,omitempty"`
	WindowFailures  int64                  `protobuf:"varint,4,opt,name=window_failures,json=windowFailures,proto3" json:"window_failures,omitempty"`
	WindowSuccesses int64                  `protobuf:"varint,5,opt,name=window_successes,json=windowSuccesses,proto3" json:"window_successes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BreakerStatsResp) Reset() {
	*x = BreakerStatsResp{}
	mi := &file_rpc_proxy_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakerStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakerStatsResp) ProtoMessage() {}

func (x *BreakerStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakerStatsResp.ProtoReflect.Descriptor instead.
func (*BreakerStatsResp) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *BreakerStatsResp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BreakerStatsResp) GetTotalFailures() int64 {
	if x != nil {
		return x.TotalFailures
	}
	return 0
}

func (x *BreakerStatsResp) GetTotalSuccesses() int64 {
	if x != nil {
		return x.TotalSuccesses
	}
	return 0
}

func (x *BreakerStatsResp) GetWindowFailures() int64 {
	if x != nil {
		return x.WindowFailures
	}
	return 0
}

func (x *BreakerStatsResp) GetWindowSuccesses() int64 {
	if x != nil {
		return x.WindowSuccesses
	}
	return 0
}

var File_rpc_proxy_proxy_proto protoreflect.FileDescriptor

const file_rpc_proxy_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15rpc/proxy/proxy.proto\x12\trpc.proxy\"\v\n" +
	"\tStatusReq\"\xe4\x01\n" +
	"\n" +
	"ForwardReq\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\frequest_body\x18\x03 \x01(\fR\vrequestBody\x12<\n" +
	"\aheaders\x18\x04 \x03(\v2\".rpc.proxy.ForwardReq.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x02\n" +
	"\vForwardResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rresponse_body\x18\x02 \x01(\fR\fresponseBody\x12=\n" +
	"\aheaders\x18\x03 \x03(\v2#.rpc.proxy.ForwardResp.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x05R\x10completionTokens\x12\x1f\n" +
	"\vupstream_id\x18\a \x01(\tR\n" +
	"upstreamId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\vProxyStatus\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0factive_requests\x18\x02 \x01(\x05R\x0eactiveRequests\x12%\n" +
	"\x0eprovider_count\x18\x03 \x01(\x05R\rproviderCount\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\"6\n" +
	"\x0fBreakerStatsReq\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\"\xcc\x01\n" +
	"\x10BreakerStatsResp\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12%\n" +
	"\x0etotal_failures\x18\x02 \x01(\x03R\rtotalFailures\x12'\n" +
	"\x0ftotal_successes\x18\x03 \x01(\x03R\x0etotalSuccesses\x12'\n" +
	"\x0fwindow_failures\x18\x04 \x01(\x03R\x0ewindowFailures\x12)\n" +
	"\x10window_successes\x18\x05 \x01(\x03R\x0fwindowSuccesses2\xcf\x01\n" +
	"\fProxyService\x128\n" +
	"\aForward\x12\x15.rpc.proxy.ForwardReq\x1a\x16.rpc.proxy.ForwardResp\x129\n" +
	"\tGetStatus\x12\x14.rpc.proxy.StatusReq\x1a\x16.rpc.proxy.ProxyStatus\x12J\n" +
	"\x0fGetBreakerStats\x12\x1a.rpc.proxy.BreakerStatsReq\x1a\x1b.rpc.proxy.BreakerStatsRespB$Z\"github.com/ragent/router/rpc/proxyb\x06proto3"

var (
	file_rpc_proxy_proxy_proto_rawDescOnce sync.Once
	file_rpc_proxy_proxy_proto_rawDescData []byte
)

func file_rpc_proxy_proxy_proto_rawDescGZIP() []byte {
	file_rpc_proxy_proxy_proto_rawDescOnce.Do(func() {
		file_rpc_proxy_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proxy_proxy_proto_rawDesc), len(file_rpc_proxy_proxy_proto_rawDesc)))
	})
	return file_rpc_proxy_proxy_proto_rawDescData
}

var file_rpc_proxy_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_proxy_proxy_proto_goTypes = []any{
	(*StatusReq)(nil),        // 0: rpc.proxy.StatusReq
	(*ForwardReq)(nil),       // 1: rpc.proxy.ForwardReq
	(*ForwardResp)(nil),      // 2: rpc.proxy.ForwardResp
	(*ProxyStatus)(nil),      // 3: rpc.proxy.ProxyStatus
	(*BreakerStatsReq)(nil),  // 4: rpc.proxy.BreakerStatsReq
	(*BreakerStatsResp)(nil), // 5: rpc.proxy.BreakerStatsResp
	nil,                      // 6: rpc.proxy.ForwardReq.HeadersEntry
	nil,                      // 7: rpc.proxy.ForwardResp.HeadersEntry
}
var file_rpc_proxy_proxy_proto_depIdxs = []int32{
	6, // 0: rpc.proxy.ForwardReq.headers:type_name -> rpc.proxy.ForwardReq.HeadersEntry
	7, // 1: rpc.proxy.ForwardResp.headers:type_name -> rpc.proxy.ForwardResp.HeadersEntry
	1, // 2: rpc.proxy.ProxyService.Forward:input_type -> rpc.proxy.ForwardReq
	0, // 3: rpc.proxy.ProxyService.GetStatus:input_type -> rpc.proxy.StatusReq
	4, // 4: rpc.proxy.ProxyService.GetBreakerStats:input_type -> rpc.proxy.BreakerStatsReq
	2, // 5: rpc.proxy.ProxyService.Forward:output_type -> rpc.proxy.ForwardResp
	3, // 6: rpc.proxy.ProxyService.GetStatus:output_type -> rpc.proxy.ProxyStatus
	5, // 7: rpc.proxy.ProxyService.GetBreakerStats:output_type -> rpc.proxy.BreakerStatsResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_proxy_proxy_proto_init() }
func file_rpc_proxy_proxy_proto_init() {
	if File_rpc_proxy_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proxy_proxy_proto_rawDesc), len(file_rpc_proxy_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proxy_proxy_proto_goTypes,
		DependencyIndexes: file_rpc_proxy_proxy_proto_depIdxs,
		MessageInfos:      file_rpc_proxy_proxy_proto_msgTypes,
	}.Build()
	File_rpc_proxy_proxy_proto = out.File
	file_rpc_proxy_proxy_proto_goTypes = nil
	file_rpc_proxy_proxy_proto_depIdxs = nil
}
