// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: rpc/proxy/proxy.proto

package proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyService_Forward_FullMethodName         = "/rpc.proxy.ProxyService/Forward"
	ProxyService_GetStatus_FullMethodName       = "/rpc.proxy.ProxyService/GetStatus"
	ProxyService_GetBreakerStats_FullMethodName = "/rpc.proxy.ProxyService/GetBreakerStats"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProxyService 代理转发 RPC 服务。
type ProxyServiceClient interface {
	// Forward 转发请求到上游供应商（Unary，返回完整响应）。
	Forward(ctx context.Context, in *ForwardReq, opts ...grpc.CallOption) (*ForwardResp, error)
	// GetStatus 获取代理状态。
	GetStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*ProxyStatus, error)
	// GetBreakerStats 获取熔断器统计。
	GetBreakerStats(ctx context.Context, in *BreakerStatsReq, opts ...grpc.CallOption) (*BreakerStatsResp, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) Forward(ctx context.Context, in *ForwardReq, opts ...grpc.CallOption) (*ForwardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResp)
	err := c.cc.Invoke(ctx, ProxyService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*ProxyStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyStatus)
	err := c.cc.Invoke(ctx, ProxyService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetBreakerStats(ctx context.Context, in *BreakerStatsReq, opts ...grpc.CallOption) (*BreakerStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BreakerStatsResp)
	err := c.cc.Invoke(ctx, ProxyService_GetBreakerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
//
// ProxyService 代理转发 RPC 服务。
type ProxyServiceServer interface {
	// Forward 转发请求到上游供应商（Unary，返回完整响应）。
	Forward(context.Context, *ForwardReq) (*ForwardResp, error)
	// GetStatus 获取代理状态。
	GetStatus(context.Context, *StatusReq) (*ProxyStatus, error)
	// GetBreakerStats 获取熔断器统计。
	GetBreakerStats(context.Context, *BreakerStatsReq) (*BreakerStatsResp, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) Forward(context.Context, *ForwardReq) (*ForwardResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedProxyServiceServer) GetStatus(context.Context, *StatusReq) (*ProxyStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedProxyServiceServer) GetBreakerStats(context.Context, *BreakerStatsReq) (*BreakerStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBreakerStats not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).Forward(ctx, req.(*ForwardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetStatus(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetBreakerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BreakerStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetBreakerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetBreakerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetBreakerStats(ctx, req.(*BreakerStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.proxy.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _ProxyService_Forward_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ProxyService_GetStatus_Handler,
		},
		{
			MethodName: "GetBreakerStats",
			Handler:    _ProxyService_GetBreakerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proxy/proxy.proto",
}
