// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: rpc/router/router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyReq) Reset() {
	*x = ClassifyReq{}
	mi := &file_rpc_router_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyReq) ProtoMessage() {}

func (x *ClassifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_router_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyReq.ProtoReflect.Descriptor instead.
func (*ClassifyReq) Descriptor() ([]byte, []int) {
	return file_rpc_router_router_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ClassifyReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ClassifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"` // 匹配的供应商名
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                             // keyword / embedding / llm / fallback
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // 置信度 (0.0-1.0)
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`         // 分类耗时
	RouteReason   string                 `protobuf:"bytes,5,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`    // 路由原因描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResp) Reset() {
	*x = ClassifyResp{}
	mi := &file_rpc_router_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResp) ProtoMessage() {}

func (x *ClassifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_router_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResp.ProtoReflect.Descriptor instead.
func (*ClassifyResp) Descriptor() ([]byte, []int) {
	return file_rpc_router_router_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResp) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ClassifyResp) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ClassifyResp) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyResp) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ClassifyResp) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

type StatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsReq) Reset() {
	*x = StatsReq{}
	mi := &file_rpc_router_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReq) ProtoMessage() {}

func (x *StatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_router_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReq.ProtoReflect.Descriptor instead.
func (*StatsReq) Descriptor() ([]byte, []int) {
	return file_rpc_router_router_proto_rawDescGZIP(), []int{2}
}

type StatsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeywordHits    int64                  `protobuf:"varint,1,opt,name=keyword_hits,json=keywordHits,proto3" json:"keyword_hits,omitempty"`
	EmbeddingHits  int64                  `protobuf:"varint,2,opt,name=embedding_hits,json=embeddingHits,proto3" json:"embedding_hits,omitempty"`
	ClassifierHits int64                  `protobuf:"varint,3,opt,name=classifier_hits,json=classifierHits,proto3" json:"classifier_hits,omitempty"`
	FallbackHits   int64                  `protobuf:"varint,4,opt,name=fallback_hits,json=fallbackHits,proto3" json:"fallback_hits,omitempty"`
	Total          int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	CacheSize      int64                  `protobuf:"varint,6,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResp) Reset() {
	*x = StatsResp{}
	mi := &file_rpc_router_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResp) ProtoMessage() {}

func (x *StatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_router_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResp.ProtoReflect.Descriptor instead.
func (*StatsResp) Descriptor() ([]byte, []int) {
	return file_rpc_router_router_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResp) GetKeywordHits() int64 {
	if x != nil {
		return x.KeywordHits
	}
	return 0
}

func (x *StatsResp) GetEmbeddingHits() int64 {
	if x != nil {
		return x.EmbeddingHits
	}
	return 0
}

func (x *StatsResp) GetClassifierHits() int64 {
	if x != nil {
		return x.ClassifierHits
	}
	return 0
}

func (x *StatsResp) GetFallbackHits() int64 {
	if x != nil {
		return x.FallbackHits
	}
	return 0
}

func (x *StatsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatsResp) GetCacheSize() int64 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

var File_rpc_router_router_proto protoreflect.FileDescriptor

const file_rpc_router_router_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/router/router.proto\x12\n" +
	"rpc.router\";\n" +
	"\vClassifyReq\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"\xb1\x01\n" +
	"\fClassifyResp\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12!\n" +
	"\froute_reason\x18\x05 \x01(\tR\vrouteReason\"\n" +
	"\n" +
	"\bStatsReq\"\xd8\x01\n" +
	"\tStatsResp\x12!\n" +
	"\fkeyword_hits\x18\x01 \x01(\x03R\vkeywordHits\x12%\n" +
	"\x0eembedding_hits\x18\x02 \x01(\x03R\rembeddingHits\x12'\n" +
	"\x0fclassifier_hits\x18\x03 \x01(\x03R\x0eclassifierHits\x12#\n" +
	"\rfallback_hits\x18\x04 \x01(\x03R\ffallbackHits\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x06 \x01(\x03R\tcacheSize2\x8e\x01\n" +
	"\rRouterService\x12=\n" +
	"\bClassify\x12\x17.rpc.router.ClassifyReq\x1a\x18.rpc.router.ClassifyResp\x12>\n" +
	"\x0fGetRoutingStats\x12\x14.rpc.router.StatsReq\x1a\x15.rpc.router.StatsRespB%Z#github.com/ragent/router/rpc/routerb\x06proto3"

var (
	file_rpc_router_router_proto_rawDescOnce sync.Once
	file_rpc_router_router_proto_rawDescData []byte
)

func file_rpc_router_router_proto_rawDescGZIP() []byte {
	file_rpc_router_router_proto_rawDescOnce.Do(func() {
		file_rpc_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_router_router_proto_rawDesc), len(file_rpc_router_router_proto_rawDesc)))
	})
	return file_rpc_router_router_proto_rawDescData
}

var file_rpc_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_router_router_proto_goTypes = []any{
	(*ClassifyReq)(nil),  // 0: rpc.router.ClassifyReq
	(*ClassifyResp)(nil), // 1: rpc.router.ClassifyResp
	(*StatsReq)(nil),     // 2: rpc.router.StatsReq
	(*StatsResp)(nil),    // 3: rpc.router.StatsResp
}
var file_rpc_router_router_proto_depIdxs = []int32{
	0, // 0: rpc.router.RouterService.Classify:input_type -> rpc.router.ClassifyReq
	2, // 1: rpc.router.RouterService.GetRoutingStats:input_type -> rpc.router.StatsReq
	1, // 2: rpc.router.RouterService.Classify:output_type -> rpc.router.ClassifyResp
	3, // 3: rpc.router.RouterService.GetRoutingStats:output_type -> rpc.router.StatsResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_router_router_proto_init() }
func file_rpc_router_router_proto_init() {
	if File_rpc_router_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_router_router_proto_rawDesc), len(file_rpc_router_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_router_router_proto_goTypes,
		DependencyIndexes: file_rpc_router_router_proto_depIdxs,
		MessageInfos:      file_rpc_router_router_proto_msgTypes,
	}.Build()
	File_rpc_router_router_proto = out.File
	file_rpc_router_router_proto_goTypes = nil
	file_rpc_router_router_proto_depIdxs = nil
}
