// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: rpc/router/router.proto

package router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterService_Classify_FullMethodName        = "/rpc.router.RouterService/Classify"
	RouterService_GetRoutingStats_FullMethodName = "/rpc.router.RouterService/GetRoutingStats"
)

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouterService 路由引擎 RPC 服务。
type RouterServiceClient interface {
	// Classify 对用户提示词进行意图分类，返回最佳供应商。
	Classify(ctx context.Context, in *ClassifyReq, opts ...grpc.CallOption) (*ClassifyResp, error)
	// GetRoutingStats 获取路由统计信息。
	GetRoutingStats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*StatsResp, error)
}

type routerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterServiceClient(cc grpc.ClientConnInterface) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) Classify(ctx context.Context, in *ClassifyReq, opts ...grpc.CallOption) (*ClassifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResp)
	err := c.cc.Invoke(ctx, RouterService_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetRoutingStats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*StatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResp)
	err := c.cc.Invoke(ctx, RouterService_GetRoutingStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServiceServer is the server API for RouterService service.
// All implementations must embed UnimplementedRouterServiceServer
// for forward compatibility.
//
// RouterService 路由引擎 RPC 服务。
type RouterServiceServer interface {
	// Classify 对用户提示词进行意图分类，返回最佳供应商。
	Classify(context.Context, *ClassifyReq) (*ClassifyResp, error)
	// GetRoutingStats 获取路由统计信息。
	GetRoutingStats(context.Context, *StatsReq) (*StatsResp, error)
	mustEmbedUnimplementedRouterServiceServer()
}

// UnimplementedRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServiceServer struct{}

func (UnimplementedRouterServiceServer) Classify(context.Context, *ClassifyReq) (*ClassifyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedRouterServiceServer) GetRoutingStats(context.Context, *StatsReq) (*StatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingStats not implemented")
}
func (UnimplementedRouterServiceServer) mustEmbedUnimplementedRouterServiceServer() {}
func (UnimplementedRouterServiceServer) testEmbeddedByValue()                       {}

// UnsafeRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServiceServer will
// result in compilation errors.
type UnsafeRouterServiceServer interface {
	mustEmbedUnimplementedRouterServiceServer()
}

func RegisterRouterServiceServer(s grpc.ServiceRegistrar, srv RouterServiceServer) {
	// If the following call panics, it indicates UnimplementedRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterService_ServiceDesc, srv)
}

func _RouterService_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).Classify(ctx, req.(*ClassifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetRoutingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetRoutingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetRoutingStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetRoutingStats(ctx, req.(*StatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterService_ServiceDesc is the grpc.ServiceDesc for RouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.router.RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _RouterService_Classify_Handler,
		},
		{
			MethodName: "GetRoutingStats",
			Handler:    _RouterService_GetRoutingStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/router/router.proto",
}
