FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/provider ./services/provider

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/provider /app/provider
COPY --from=builder /app/services/provider/etc /app/etc
EXPOSE 8081
WORKDIR /app
CMD ["./provider", "-f", "etc/provider.yaml"]
