FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.work .
COPY shared/ shared/
COPY rpc/ rpc/
COPY services/ services/
WORKDIR /build/services/api
RUN GOPROXY=https://goproxy.cn,direct go mod download
RUN CGO_ENABLED=0 go build -o /app/api .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/api /app/api
COPY services/api/etc /app/etc
WORKDIR /app
CMD ["./api", "-f", "etc/api.yaml"]
