FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.work .
COPY shared/ shared/
COPY rpc/ rpc/
COPY services/ services/
WORKDIR /build/services/proxy
RUN GOPROXY=https://goproxy.cn,direct go mod download
RUN CGO_ENABLED=0 go build -o /app/proxy .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/proxy /app/proxy
COPY services/proxy/etc /app/etc
WORKDIR /app
CMD ["./proxy", "-f", "etc/proxy.yaml"]
