FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.work .
COPY shared/ shared/
COPY rpc/ rpc/
COPY services/ services/
WORKDIR /build/services/router
RUN GOPROXY=https://goproxy.cn,direct go mod download
RUN CGO_ENABLED=0 go build -o /app/router .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/router /app/router
COPY services/router/etc /app/etc
WORKDIR /app
CMD ["./router", "-f", "etc/router.yaml"]
