FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/router ./services/router

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/router /app/router
COPY --from=builder /app/services/router/etc /app/etc
EXPOSE 8082
WORKDIR /app
CMD ["./router", "-f", "etc/router.yaml"]
