FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/api ./services/api

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/api /app/api
COPY --from=builder /app/services/api/etc /app/etc
EXPOSE 15722
WORKDIR /app
CMD ["./api", "-f", "etc/api.yaml"]
