// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: grpc/proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusRequest 获取状态请求（当前无参数，保留扩展位）。
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_grpc_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_gateway_proto_rawDescGZIP(), []int{0}
}

// StatusResponse 网关状态响应。
type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                      // 网关版本号
	UptimeSeconds  int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`    // 运行时长（秒）
	TotalRequests  int64                  `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`    // 累计处理请求数
	ActiveRequests int32                  `protobuf:"varint,4,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"` // 当前活跃请求数
	ProviderCount  int32                  `protobuf:"varint,5,opt,name=provider_count,json=providerCount,proto3" json:"provider_count,omitempty"`    // 已注册供应商数
	Healthy        bool                   `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`                                     // 整体健康状态
	ErrorRate      float64                `protobuf:"fixed64,7,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`               // 最近窗口错误率
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_grpc_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatusResponse) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *StatusResponse) GetProviderCount() int32 {
	if x != nil {
		return x.ProviderCount
	}
	return 0
}

func (x *StatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *StatusResponse) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

// MetricsRequest 订阅指标流的请求（当前无参数，保留扩展位）。
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_grpc_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_gateway_proto_rawDescGZIP(), []int{2}
}

// MetricsUpdate 单次指标更新（流式推送）。
type MetricsUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // Unix 时间戳（毫秒）
	RequestsPerSec float64                `protobuf:"fixed64,2,opt,name=requests_per_sec,json=requestsPerSec,proto3" json:"requests_per_sec,omitempty"` // 每秒请求数（QPS）
	AvgLatencyMs   float64                `protobuf:"fixed64,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`       // 平均延迟（毫秒）
	ErrorRate      float64                `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`                  // 错误率
	ActiveRequests int32                  `protobuf:"varint,5,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`    // 当前活跃请求数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsUpdate) Reset() {
	*x = MetricsUpdate{}
	mi := &file_grpc_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUpdate) ProtoMessage() {}

func (x *MetricsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUpdate.ProtoReflect.Descriptor instead.
func (*MetricsUpdate) Descriptor() ([]byte, []int) {
	return file_grpc_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsUpdate) GetRequestsPerSec() float64 {
	if x != nil {
		return x.RequestsPerSec
	}
	return 0
}

func (x *MetricsUpdate) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *MetricsUpdate) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *MetricsUpdate) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

// ClassifyRequest 意图分类请求。
type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"` // 用户提示词
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`   // 请求的模型名（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_grpc_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ClassifyRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ClassifyRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// ClassifyResponse 意图分类响应。
type ClassifyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchedProvider string                 `protobuf:"bytes,1,opt,name=matched_provider,json=matchedProvider,proto3" json:"matched_provider,omitempty"` // 匹配的供应商名
	Strategy        string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                                      // 路由策略: keyword / embedding / llm / fallback
	Confidence      float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                                // 分类置信度 (0.0-1.0)
	LatencyMs       int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                  // 分类耗时（毫秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_grpc_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ClassifyResponse) GetMatchedProvider() string {
	if x != nil {
		return x.MatchedProvider
	}
	return ""
}

func (x *ClassifyResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ClassifyResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_grpc_proto_gateway_proto protoreflect.FileDescriptor

const file_grpc_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/proto/gateway.proto\x12\vragent.grpc\"\x0f\n" +
	"\rStatusRequest\"\x81\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0factive_requests\x18\x04 \x01(\x05R\x0eactiveRequests\x12%\n" +
	"\x0eprovider_count\x18\x05 \x01(\x05R\rproviderCount\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"error_rate\x18\a \x01(\x01R\terrorRate\"\x10\n" +
	"\x0eMetricsRequest\"\xc5\x01\n" +
	"\rMetricsUpdate\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10requests_per_sec\x18\x02 \x01(\x01R\x0erequestsPerSec\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x01R\favgLatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12'\n" +
	"\x0factive_requests\x18\x05 \x01(\x05R\x0eactiveRequests\"?\n" +
	"\x0fClassifyRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"\x98\x01\n" +
	"\x10ClassifyResponse\x12)\n" +
	"\x10matched_provider\x18\x01 \x01(\tR\x0fmatchedProvider\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs2\xf1\x01\n" +
	"\x0eGatewayService\x12D\n" +
	"\tGetStatus\x12\x1a.ragent.grpc.StatusRequest\x1a\x1b.ragent.grpc.StatusResponse\x12J\n" +
	"\rStreamMetrics\x12\x1b.ragent.grpc.MetricsRequest\x1a\x1a.ragent.grpc.MetricsUpdate0\x01\x12M\n" +
	"\x0eClassifyIntent\x12\x1c.ragent.grpc.ClassifyRequest\x1a\x1d.ragent.grpc.ClassifyResponseB%Z#github.com/ragent/router/grpc/protob\x06proto3"

var (
	file_grpc_proto_gateway_proto_rawDescOnce sync.Once
	file_grpc_proto_gateway_proto_rawDescData []byte
)

func file_grpc_proto_gateway_proto_rawDescGZIP() []byte {
	file_grpc_proto_gateway_proto_rawDescOnce.Do(func() {
		file_grpc_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_gateway_proto_rawDesc), len(file_grpc_proto_gateway_proto_rawDesc)))
	})
	return file_grpc_proto_gateway_proto_rawDescData
}

var file_grpc_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_proto_gateway_proto_goTypes = []any{
	(*StatusRequest)(nil),    // 0: ragent.grpc.StatusRequest
	(*StatusResponse)(nil),   // 1: ragent.grpc.StatusResponse
	(*MetricsRequest)(nil),   // 2: ragent.grpc.MetricsRequest
	(*MetricsUpdate)(nil),    // 3: ragent.grpc.MetricsUpdate
	(*ClassifyRequest)(nil),  // 4: ragent.grpc.ClassifyRequest
	(*ClassifyResponse)(nil), // 5: ragent.grpc.ClassifyResponse
}
var file_grpc_proto_gateway_proto_depIdxs = []int32{
	0, // 0: ragent.grpc.GatewayService.GetStatus:input_type -> ragent.grpc.StatusRequest
	2, // 1: ragent.grpc.GatewayService.StreamMetrics:input_type -> ragent.grpc.MetricsRequest
	4, // 2: ragent.grpc.GatewayService.ClassifyIntent:input_type -> ragent.grpc.ClassifyRequest
	1, // 3: ragent.grpc.GatewayService.GetStatus:output_type -> ragent.grpc.StatusResponse
	3, // 4: ragent.grpc.GatewayService.StreamMetrics:output_type -> ragent.grpc.MetricsUpdate
	5, // 5: ragent.grpc.GatewayService.ClassifyIntent:output_type -> ragent.grpc.ClassifyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_gateway_proto_init() }
func file_grpc_proto_gateway_proto_init() {
	if File_grpc_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_gateway_proto_rawDesc), len(file_grpc_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_gateway_proto_goTypes,
		DependencyIndexes: file_grpc_proto_gateway_proto_depIdxs,
		MessageInfos:      file_grpc_proto_gateway_proto_msgTypes,
	}.Build()
	File_grpc_proto_gateway_proto = out.File
	file_grpc_proto_gateway_proto_goTypes = nil
	file_grpc_proto_gateway_proto_depIdxs = nil
}
