// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: rpc/provider/provider.proto

package provider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_GetChannel_FullMethodName          = "/rpc.provider.ProviderService/GetChannel"
	ProviderService_ListChannels_FullMethodName        = "/rpc.provider.ProviderService/ListChannels"
	ProviderService_CheckHealth_FullMethodName         = "/rpc.provider.ProviderService/CheckHealth"
	ProviderService_GetHealthyProviders_FullMethodName = "/rpc.provider.ProviderService/GetHealthyProviders"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderService 渠道管理 RPC 服务。
type ProviderServiceClient interface {
	// GetChannel 获取单个渠道信息。
	GetChannel(ctx context.Context, in *GetChannelReq, opts ...grpc.CallOption) (*ChannelInfo, error)
	// ListChannels 获取渠道列表。
	ListChannels(ctx context.Context, in *ListChannelsReq, opts ...grpc.CallOption) (*ListChannelsResp, error)
	// CheckHealth 检查渠道健康状态。
	CheckHealth(ctx context.Context, in *CheckHealthReq, opts ...grpc.CallOption) (*CheckHealthResp, error)
	// GetHealthyProviders 获取健康供应商列表（供路由使用）。
	GetHealthyProviders(ctx context.Context, in *GetHealthyReq, opts ...grpc.CallOption) (*GetHealthyResp, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) GetChannel(ctx context.Context, in *GetChannelReq, opts ...grpc.CallOption) (*ChannelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelInfo)
	err := c.cc.Invoke(ctx, ProviderService_GetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListChannels(ctx context.Context, in *ListChannelsReq, opts ...grpc.CallOption) (*ListChannelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResp)
	err := c.cc.Invoke(ctx, ProviderService_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CheckHealth(ctx context.Context, in *CheckHealthReq, opts ...grpc.CallOption) (*CheckHealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthResp)
	err := c.cc.Invoke(ctx, ProviderService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetHealthyProviders(ctx context.Context, in *GetHealthyReq, opts ...grpc.CallOption) (*GetHealthyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthyResp)
	err := c.cc.Invoke(ctx, ProviderService_GetHealthyProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// ProviderService 渠道管理 RPC 服务。
type ProviderServiceServer interface {
	// GetChannel 获取单个渠道信息。
	GetChannel(context.Context, *GetChannelReq) (*ChannelInfo, error)
	// ListChannels 获取渠道列表。
	ListChannels(context.Context, *ListChannelsReq) (*ListChannelsResp, error)
	// CheckHealth 检查渠道健康状态。
	CheckHealth(context.Context, *CheckHealthReq) (*CheckHealthResp, error)
	// GetHealthyProviders 获取健康供应商列表（供路由使用）。
	GetHealthyProviders(context.Context, *GetHealthyReq) (*GetHealthyResp, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) GetChannel(context.Context, *GetChannelReq) (*ChannelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedProviderServiceServer) ListChannels(context.Context, *ListChannelsReq) (*ListChannelsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedProviderServiceServer) CheckHealth(context.Context, *CheckHealthReq) (*CheckHealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedProviderServiceServer) GetHealthyProviders(context.Context, *GetHealthyReq) (*GetHealthyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealthyProviders not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetChannel(ctx, req.(*GetChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListChannels(ctx, req.(*ListChannelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CheckHealth(ctx, req.(*CheckHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetHealthyProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetHealthyProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetHealthyProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetHealthyProviders(ctx, req.(*GetHealthyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.provider.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChannel",
			Handler:    _ProviderService_GetChannel_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _ProviderService_ListChannels_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _ProviderService_CheckHealth_Handler,
		},
		{
			MethodName: "GetHealthyProviders",
			Handler:    _ProviderService_GetHealthyProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/provider/provider.proto",
}
