// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: rpc/provider/provider.proto

package provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelReq) Reset() {
	*x = GetChannelReq{}
	mi := &file_rpc_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelReq) ProtoMessage() {}

func (x *GetChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelReq.ProtoReflect.Descriptor instead.
func (*GetChannelReq) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GetChannelReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Models        string                 `protobuf:"bytes,4,opt,name=models,proto3" json:"models,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 1=启用, 2=禁用, 3=自动禁用
	Weight        int32                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      int64                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Group         string                 `protobuf:"bytes,8,opt,name=group,proto3" json:"group,omitempty"`
	ResponseTime  int32                  `protobuf:"varint,9,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"` // 毫秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_rpc_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ChannelInfo) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *ChannelInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ChannelInfo) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ChannelInfo) GetResponseTime() int32 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

type ListChannelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsReq) Reset() {
	*x = ListChannelsReq{}
	mi := &file_rpc_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsReq) ProtoMessage() {}

func (x *ListChannelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsReq.ProtoReflect.Descriptor instead.
func (*ListChannelsReq) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChannelsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChannelsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelInfo         `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResp) Reset() {
	*x = ListChannelsResp{}
	mi := &file_rpc_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResp) ProtoMessage() {}

func (x *ListChannelsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResp.ProtoReflect.Descriptor instead.
func (*ListChannelsResp) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ListChannelsResp) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ListChannelsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckHealthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthReq) Reset() {
	*x = CheckHealthReq{}
	mi := &file_rpc_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthReq) ProtoMessage() {}

func (x *CheckHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthReq.ProtoReflect.Descriptor instead.
func (*CheckHealthReq) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{4}
}

func (x *CheckHealthReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type CheckHealthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResp) Reset() {
	*x = CheckHealthResp{}
	mi := &file_rpc_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResp) ProtoMessage() {}

func (x *CheckHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResp.ProtoReflect.Descriptor instead.
func (*CheckHealthResp) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *CheckHealthResp) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *CheckHealthResp) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CheckHealthResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetHealthyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // 按模型过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthyReq) Reset() {
	*x = GetHealthyReq{}
	mi := &file_rpc_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthyReq) ProtoMessage() {}

func (x *GetHealthyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthyReq.ProtoReflect.Descriptor instead.
func (*GetHealthyReq) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetHealthyReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetHealthyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ChannelInfo         `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthyResp) Reset() {
	*x = GetHealthyResp{}
	mi := &file_rpc_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthyResp) ProtoMessage() {}

func (x *GetHealthyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthyResp.ProtoReflect.Descriptor instead.
func (*GetHealthyResp) Descriptor() ([]byte, []int) {
	return file_rpc_provider_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetHealthyResp) GetProviders() []*ChannelInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_rpc_provider_provider_proto protoreflect.FileDescriptor

const file_rpc_provider_provider_proto_rawDesc = "" +
	"\n" +
	"\x1brpc/provider/provider.proto\x12\frpc.provider\"\x1f\n" +
	"\rGetChannelReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xeb\x01\n" +
	"\vChannelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06models\x18\x04 \x01(\tR\x06models\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x03R\bpriority\x12\x14\n" +
	"\x05group\x18\b \x01(\tR\x05group\x12#\n" +
	"\rresponse_time\x18\t \x01(\x05R\fresponseTime\"B\n" +
	"\x0fListChannelsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"_\n" +
	"\x10ListChannelsResp\x125\n" +
	"\bchannels\x18\x01 \x03(\v2\x19.rpc.provider.ChannelInfoR\bchannels\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"/\n" +
	"\x0eCheckHealthReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId\"`\n" +
	"\x0fCheckHealthResp\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x05R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"%\n" +
	"\rGetHealthyReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"I\n" +
	"\x0eGetHealthyResp\x127\n" +
	"\tproviders\x18\x01 \x03(\v2\x19.rpc.provider.ChannelInfoR\tproviders2\xc4\x02\n" +
	"\x0fProviderService\x12D\n" +
	"\n" +
	"GetChannel\x12\x1b.rpc.provider.GetChannelReq\x1a\x19.rpc.provider.ChannelInfo\x12M\n" +
	"\fListChannels\x12\x1d.rpc.provider.ListChannelsReq\x1a\x1e.rpc.provider.ListChannelsResp\x12J\n" +
	"\vCheckHealth\x12\x1c.rpc.provider.CheckHealthReq\x1a\x1d.rpc.provider.CheckHealthResp\x12P\n" +
	"\x13GetHealthyProviders\x12\x1b.rpc.provider.GetHealthyReq\x1a\x1c.rpc.provider.GetHealthyRespB'Z%github.com/ragent/router/rpc/providerb\x06proto3"

var (
	file_rpc_provider_provider_proto_rawDescOnce sync.Once
	file_rpc_provider_provider_proto_rawDescData []byte
)

func file_rpc_provider_provider_proto_rawDescGZIP() []byte {
	file_rpc_provider_provider_proto_rawDescOnce.Do(func() {
		file_rpc_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_provider_provider_proto_rawDesc), len(file_rpc_provider_provider_proto_rawDesc)))
	})
	return file_rpc_provider_provider_proto_rawDescData
}

var file_rpc_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_provider_provider_proto_goTypes = []any{
	(*GetChannelReq)(nil),    // 0: rpc.provider.GetChannelReq
	(*ChannelInfo)(nil),      // 1: rpc.provider.ChannelInfo
	(*ListChannelsReq)(nil),  // 2: rpc.provider.ListChannelsReq
	(*ListChannelsResp)(nil), // 3: rpc.provider.ListChannelsResp
	(*CheckHealthReq)(nil),   // 4: rpc.provider.CheckHealthReq
	(*CheckHealthResp)(nil),  // 5: rpc.provider.CheckHealthResp
	(*GetHealthyReq)(nil),    // 6: rpc.provider.GetHealthyReq
	(*GetHealthyResp)(nil),   // 7: rpc.provider.GetHealthyResp
}
var file_rpc_provider_provider_proto_depIdxs = []int32{
	1, // 0: rpc.provider.ListChannelsResp.channels:type_name -> rpc.provider.ChannelInfo
	1, // 1: rpc.provider.GetHealthyResp.providers:type_name -> rpc.provider.ChannelInfo
	0, // 2: rpc.provider.ProviderService.GetChannel:input_type -> rpc.provider.GetChannelReq
	2, // 3: rpc.provider.ProviderService.ListChannels:input_type -> rpc.provider.ListChannelsReq
	4, // 4: rpc.provider.ProviderService.CheckHealth:input_type -> rpc.provider.CheckHealthReq
	6, // 5: rpc.provider.ProviderService.GetHealthyProviders:input_type -> rpc.provider.GetHealthyReq
	1, // 6: rpc.provider.ProviderService.GetChannel:output_type -> rpc.provider.ChannelInfo
	3, // 7: rpc.provider.ProviderService.ListChannels:output_type -> rpc.provider.ListChannelsResp
	5, // 8: rpc.provider.ProviderService.CheckHealth:output_type -> rpc.provider.CheckHealthResp
	7, // 9: rpc.provider.ProviderService.GetHealthyProviders:output_type -> rpc.provider.GetHealthyResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_provider_provider_proto_init() }
func file_rpc_provider_provider_proto_init() {
	if File_rpc_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_provider_provider_proto_rawDesc), len(file_rpc_provider_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_provider_provider_proto_goTypes,
		DependencyIndexes: file_rpc_provider_provider_proto_depIdxs,
		MessageInfos:      file_rpc_provider_provider_proto_msgTypes,
	}.Build()
	File_rpc_provider_provider_proto = out.File
	file_rpc_provider_provider_proto_goTypes = nil
	file_rpc_provider_provider_proto_depIdxs = nil
}
